-- Intentionally empty. Runs only on local/CI databases (`supabase start` /
-- `db reset`), never on the live project, so anything here would make those
-- databases differ from production. The base categories come from
-- 0018_mock_data.sql and the platform commission rule (5%) from
-- 0021_commission_markup_model.sql; test fixtures are created by
-- tests/fixtures/ensureQaFixtures.ts.
